# Generated by Django 4.2.27 on 2026-01-06 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_payment_notification"),
        ("enrollments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollment",
            name="current_lesson",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="current_for_enrollments",
                to="catalog.lesson",
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Actif"),
                    ("COMPLETED", "Terminé"),
                    ("CANCELED", "Annulé"),
                ],
                default="ACTIVE",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
