# Generated by Django 4.2.27 on 2026-01-07 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enrollments", "0002_enrollment_current_lesson_enrollment_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lessonprogress",
            name="progress_percent",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
