# Generated by Django 4.2.27 on 2026-03-20 16:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("enrollments", "0003_alter_lessonprogress_progress_percent"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollment",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="enrollment",
            name="progress_percent",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="lessonprogress",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
