# Generated by Django 4.2.27 on 2026-04-23 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0002_organization_organizationinvitation_and_more"),
        (
            "enrollments",
            "0004_enrollment_created_at_enrollment_progress_percent_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="enrollment",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="enrollments",
                to="organizations.organization",
            ),
        ),
    ]
