# Generated by Django 4.2.27 on 2026-01-17 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_payment_notification"),
        ("assessments", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="quiz",
            name="is_onboarding",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="quiz",
            name="slug",
            field=models.SlugField(blank=True, max_length=80, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quizzes",
                to="catalog.course",
            ),
        ),
    ]
