# Generated by Django 4.2.27 on 2026-01-17 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0004_quiz_is_active_quiz_is_onboarding_quiz_slug_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="topic",
            field=models.CharField(
                blank=True,
                choices=[
                    ("budget", "Budget & gestion des dépenses"),
                    ("epargne", "Épargne & discipline financière"),
                    ("objectifs", "Objectifs financiers"),
                    ("flux", "Gestion des flux (revenus / dépenses)"),
                    ("habitudes", "Habitudes & comportements financiers"),
                    ("banque", "Fonctionnement bancaire"),
                    ("compte", "Comptes bancaires"),
                    ("taux", "Taux d’intérêt & inflation"),
                    ("frais", "Frais bancaires"),
                    ("paiement", "Moyens de paiement"),
                    ("credit", "Crédit"),
                    ("dette", "Gestion de la dette"),
                    ("emprunt", "Emprunt & remboursement"),
                    ("taux_credit", "Taux de crédit"),
                    ("surendettement", "Surendettement"),
                    ("investissement", "Investissement"),
                    ("placement", "Placements financiers"),
                    ("risque", "Risque & rendement"),
                    ("diversification", "Diversification"),
                    ("patrimoine", "Gestion de patrimoine"),
                    ("bourse", "Marchés financiers"),
                    ("actions", "Actions"),
                    ("obligations", "Obligations"),
                    ("immobilier", "Investissement immobilier"),
                    ("assurance", "Assurance & protection"),
                    ("epargne_securite", "Épargne de sécurité"),
                    ("risques_vie", "Gestion des risques de la vie"),
                    ("prevoyance", "Prévoyance"),
                    ("macro", "Économie générale"),
                    ("inflation", "Inflation"),
                    ("politique_monetaire", "Politique monétaire"),
                    ("croissance", "Croissance économique"),
                    ("conjoncture", "Conjoncture économique"),
                    ("entrepreneuriat", "Entrepreneuriat"),
                    ("business_model", "Business model"),
                    ("cashflow", "Cash-flow"),
                    ("revenus", "Sources de revenus"),
                    ("invest_entreprise", "Investir dans une entreprise"),
                    ("fiscalite", "Fiscalité"),
                    ("strategie", "Stratégie financière"),
                    ("planification", "Planification financière"),
                    ("psycho", "Psychologie financière"),
                    ("discipline", "Discipline financière"),
                ],
                help_text="Thème principal évalué par cette question",
                max_length=32,
            ),
        ),
    ]
