# Generated by Django 4.2.27 on 2026-03-20 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_alter_lesson_content"),
        ("assessments", "0005_question_topic"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="quiz",
            options={"ordering": ["title"]},
        ),
        migrations.AddField(
            model_name="quiz",
            name="section",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quizzes",
                to="catalog.coursesection",
            ),
        ),
    ]
