# Generated by Django 4.2.27 on 2026-04-23 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0006_alter_quiz_options_quiz_section'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attempt',
            options={'ordering': ['-started_at']},
        ),
        migrations.AddIndex(
            model_name='attempt',
            index=models.Index(fields=['quiz', 'user'], name='assessments_quiz_id_c1dd5c_idx'),
        ),
        migrations.AddIndex(
            model_name='attempt',
            index=models.Index(fields=['user', 'submitted_at'], name='assessments_user_id_b60ed7_idx'),
        ),
        migrations.AddConstraint(
            model_name='attemptanswer',
            constraint=models.UniqueConstraint(fields=('attempt', 'question'), name='uniq_attempt_question'),
        ),
    ]
