# Generated by Django 4.2.27 on 2026-07-13 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="platformsettingshistory",
            new_name="core_platfo_created_5d6c03_idx",
            old_name="core_platfo_created_idx",
        ),
        migrations.AlterField(
            model_name="platformsettings",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="platformsettingshistory",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
