# Generated by Django 4.2.27 on 2026-04-23 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0002_organization_organizationinvitation_and_more"),
        (
            "commerce",
            "0003_alter_order_options_alter_paymenttransaction_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="companyassignment",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="organizations.organization",
            ),
        ),
        migrations.AlterField(
            model_name="companylicense",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="licenses",
                to="organizations.organization",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="organizations.organization",
            ),
        ),
    ]
