# Generated by Django 4.2.27 on 2026-07-13 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("commerce", "0009_payout"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="commissionrule",
            new_name="commerce_co_scope_55e9ae_idx",
            old_name="commerce_co_scope_a3f9b8_idx",
        ),
        migrations.RenameIndex(
            model_name="commissionrule",
            new_name="commerce_co_instruc_fe6cf2_idx",
            old_name="commerce_co_instruc_1c2e4a_idx",
        ),
        migrations.RenameIndex(
            model_name="commissionrule",
            new_name="commerce_co_categor_38ed51_idx",
            old_name="commerce_co_categor_9d8e21_idx",
        ),
        migrations.RenameIndex(
            model_name="commissionrule",
            new_name="commerce_co_course__cce4b9_idx",
            old_name="commerce_co_course_5f0a72_idx",
        ),
        migrations.RenameIndex(
            model_name="payout",
            new_name="commerce_pa_instruc_a70914_idx",
            old_name="payout_instructor_idx",
        ),
        migrations.RenameIndex(
            model_name="payout",
            new_name="commerce_pa_status_b4fd40_idx",
            old_name="payout_status_period_idx",
        ),
        migrations.RenameIndex(
            model_name="payout",
            new_name="commerce_pa_created_c56fa1_idx",
            old_name="payout_created_idx",
        ),
    ]
