# Generated by Django 4.2.27 on 2026-04-23 16:46

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=180, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                ("legal_name", models.CharField(blank=True, max_length=220)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=30)),
                (
                    "country",
                    models.CharField(
                        blank=True, default="Côte d’Ivoire", max_length=80
                    ),
                ),
                ("city", models.CharField(blank=True, max_length=80)),
                ("address", models.CharField(blank=True, max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="OrganizationInvitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("OWNER", "Propriétaire"),
                            ("ADMIN", "Administrateur"),
                            ("MANAGER", "Manager"),
                            ("INSTRUCTOR", "Formateur"),
                            ("LEARNER", "Apprenant"),
                        ],
                        db_index=True,
                        default="LEARNER",
                        max_length=20,
                    ),
                ),
                (
                    "token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrganizationMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("OWNER", "Propriétaire"),
                            ("ADMIN", "Administrateur"),
                            ("MANAGER", "Manager"),
                            ("INSTRUCTOR", "Formateur"),
                            ("LEARNER", "Apprenant"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "joined_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ["organization__name", "role", "user__email"],
            },
        ),
        migrations.AlterUniqueTogether(
            name="companyinvitation",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="companyinvitation",
            name="company",
        ),
        migrations.RemoveField(
            model_name="companyinvitation",
            name="invited_by",
        ),
        migrations.AlterUniqueTogether(
            name="companymember",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="companymember",
            name="company",
        ),
        migrations.RemoveField(
            model_name="companymember",
            name="user",
        ),
    ]
