# Generated by Django 4.2.27 on 2026-04-23 16:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("enrollments", "0005_alter_enrollment_company"),
        ("commerce", "0004_alter_companyassignment_company_and_more"),
        ("catalog", "0007_alter_course_company"),
        ("organizations", "0002_organization_organizationinvitation_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Company",
        ),
        migrations.DeleteModel(
            name="CompanyInvitation",
        ),
        migrations.DeleteModel(
            name="CompanyMember",
        ),
        migrations.AddField(
            model_name="organizationmembership",
            name="invited_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="organization_memberships_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="organizationmembership",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memberships",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="organizationmembership",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="organization_memberships",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="organizationinvitation",
            name="invited_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="organization_invitations_sent",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="organizationinvitation",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invitations",
                to="organizations.organization",
            ),
        ),
        migrations.AddIndex(
            model_name="organization",
            index=models.Index(
                fields=["is_active", "name"], name="organizatio_is_acti_c047e9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="organization",
            index=models.Index(
                fields=["created_at"], name="organizatio_created_dfd536_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="organizationmembership",
            index=models.Index(
                fields=["organization", "role", "is_active"],
                name="organizatio_organiz_b3d0b8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="organizationmembership",
            index=models.Index(
                fields=["user", "role", "is_active"],
                name="organizatio_user_id_b7ae46_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="organizationmembership",
            index=models.Index(
                fields=["organization", "user"], name="organizatio_organiz_2e07c1_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="organizationmembership",
            constraint=models.UniqueConstraint(
                fields=("user", "organization", "role"),
                name="unique_user_organization_role",
            ),
        ),
        migrations.AddIndex(
            model_name="organizationinvitation",
            index=models.Index(
                fields=["organization", "email"], name="organizatio_organiz_f35a05_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="organizationinvitation",
            index=models.Index(
                fields=["organization", "role", "expires_at"],
                name="organizatio_organiz_9a3b6f_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="organizationinvitation",
            constraint=models.UniqueConstraint(
                fields=("organization", "email", "role"),
                name="unique_pending_invitation_per_role",
            ),
        ),
    ]
