# Generated by Django 4.2.27 on 2026-05-05 16:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0009_mediauploadlog"),
        ("organizations", "0003_delete_company_delete_companyinvitation_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessInterestRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "organization_name",
                    models.CharField(
                        max_length=180, verbose_name="Nom de l'organisation"
                    ),
                ),
                (
                    "contact_name",
                    models.CharField(max_length=160, verbose_name="Nom du contact"),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, verbose_name="Email professionnel"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="Téléphone"
                    ),
                ),
                (
                    "learners_count",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Apprenants estimé"
                    ),
                ),
                (
                    "message",
                    models.TextField(blank=True, verbose_name="Besoin spécifique"),
                ),
                (
                    "is_processed",
                    models.BooleanField(default=False, verbose_name="Traité"),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True,
                        related_name="business_interest_requests",
                        to="catalog.category",
                        verbose_name="Catégories souhaitées",
                    ),
                ),
                (
                    "courses",
                    models.ManyToManyField(
                        blank=True,
                        related_name="business_interest_requests",
                        to="catalog.course",
                        verbose_name="Formations souhaitées",
                    ),
                ),
            ],
            options={
                "verbose_name": "Manifestation d’intérêt entreprise",
                "verbose_name_plural": "Manifestations d’intérêt entreprises",
                "ordering": ["-created_at"],
            },
        ),
    ]
