# Generated by Django 4.2.27 on 2026-07-25 13:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("organizations", "0005_invitation_unique_partial"),
    ]

    operations = [
        migrations.AddField(
            model_name="businessinterestrequest",
            name="admin_notes",
            field=models.TextField(blank=True, verbose_name="Notes administratives"),
        ),
        migrations.AddField(
            model_name="businessinterestrequest",
            name="budget_range",
            field=models.CharField(blank=True, max_length=80, verbose_name="Budget indicatif"),
        ),
        migrations.AddField(
            model_name="businessinterestrequest",
            name="city",
            field=models.CharField(blank=True, max_length=80, verbose_name="Ville"),
        ),
        migrations.AddField(
            model_name="businessinterestrequest",
            name="consented_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Consentement donné le"),
        ),
        migrations.AddField(
            model_name="businessinterestrequest",
            name="contact_role",
            field=models.CharField(blank=True, max_length=160, verbose_name="Fonction du contact"),
        ),
        migrations.AddField(
            model_name="businessinterestrequest",
            name="country",
            field=models.CharField(
                blank=True, default="Côte d’Ivoire", max_length=80, verbose_name="Pays"
            ),
        ),
        migrations.AddField(
            model_name="businessinterestrequest",
            name="organization_type",
            field=models.CharField(
                choices=[
                    ("COMPANY", "Entreprise privée"),
                    ("PUBLIC", "Administration / institution publique"),
                    ("NGO", "ONG / association"),
                    ("EDUCATION", "École / université"),
                    ("FINANCIAL", "Institution financière"),
                    ("OTHER", "Autre organisation"),
                ],
                default="COMPANY",
                max_length=20,
                verbose_name="Type d'organisation",
            ),
        ),
        migrations.AddField(
            model_name="businessinterestrequest",
            name="plan_interest",
            field=models.CharField(
                choices=[
                    ("PRO", "Pro"),
                    ("ENTERPRISE", "Enterprise"),
                    ("DEMO", "Démonstration"),
                    ("UNSURE", "À définir avec un conseiller"),
                ],
                default="UNSURE",
                max_length=20,
                verbose_name="Offre souhaitée",
            ),
        ),
        migrations.AddField(
            model_name="businessinterestrequest",
            name="preferred_contact",
            field=models.CharField(
                choices=[("EMAIL", "E-mail"), ("PHONE", "Téléphone"), ("WHATSAPP", "WhatsApp")],
                default="EMAIL",
                max_length=20,
                verbose_name="Canal de contact préféré",
            ),
        ),
        migrations.AddField(
            model_name="businessinterestrequest",
            name="privacy_consent",
            field=models.BooleanField(default=False, verbose_name="Consentement au traitement"),
        ),
        migrations.AddField(
            model_name="businessinterestrequest",
            name="processed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Premier traitement le"),
        ),
        migrations.AddField(
            model_name="businessinterestrequest",
            name="processed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="business_interest_requests_processed",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Dernier traitement par",
            ),
        ),
        migrations.AddField(
            model_name="businessinterestrequest",
            name="source",
            field=models.CharField(
                blank=True, default="enterprise_page", max_length=80, verbose_name="Source"
            ),
        ),
        migrations.AddField(
            model_name="businessinterestrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("NEW", "Nouvelle"),
                    ("CONTACTED", "Contactée"),
                    ("QUALIFIED", "Qualifiée"),
                    ("PROPOSAL_SENT", "Devis envoyé"),
                    ("WON", "Gagnée"),
                    ("LOST", "Perdue"),
                    ("ARCHIVED", "Archivée"),
                ],
                db_index=True,
                default="NEW",
                max_length=20,
                verbose_name="Statut commercial",
            ),
        ),
        migrations.AddField(
            model_name="businessinterestrequest",
            name="timeframe",
            field=models.CharField(
                choices=[
                    ("IMMEDIATE", "Dès que possible"),
                    ("1_3_MONTHS", "Dans 1 à 3 mois"),
                    ("3_6_MONTHS", "Dans 3 à 6 mois"),
                    ("6_12_MONTHS", "Dans 6 à 12 mois"),
                    ("EXPLORING", "En phase d'exploration"),
                ],
                default="EXPLORING",
                max_length=20,
                verbose_name="Période de démarrage",
            ),
        ),
        migrations.AddField(
            model_name="businessinterestrequest",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name="businessinterestrequest",
            index=models.Index(
                fields=["status", "-created_at"], name="organizatio_status_d79f39_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="businessinterestrequest",
            index=models.Index(
                fields=["email", "-created_at"], name="organizatio_email_b7d0b4_idx"
            ),
        ),
    ]
