"""
Django settings for best_epargne project.

Generated by 'django-admin startproject' using Django 4.2.27.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from pathlib import Path

from django.contrib import staticfiles

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-r4sdxrvn&z7*csdkxwarumwm*@)r5%cxf+(42t-)@l5^q6t@e-'

# SECURITY WARNING: don't run with debug turned on in production!


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "rest_framework",
    'storages',
    "django.contrib.sites",

    # Allauth
    "allauth",
    "allauth.account",
    "allauth.socialaccount",

    "compte",
    "organizations",
    'assessments',
    'catalog',
    'certifications',
    'commerce',
    'enrollments',
    'reviews',
    'formations',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "allauth.account.middleware.AccountMiddleware",

]

ROOT_URLCONF = 'best_epargne.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'best_epargne.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases




AUTH_USER_MODEL = "compte.User"

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
        "rest_framework.authentication.TokenAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.AllowAny",
    ],
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators
AUTHENTICATION_BACKENDS = (
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
)
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

SITE_ID = 1
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ----------------
# Internationalisation
# ----------------
LANGUAGE_CODE = "fr-fr"  # tu peux passer en FR directement
TIME_ZONE = "Africa/Abidjan"
USE_I18N = True
USE_TZ = True

# ------------------------
# Statics & media / WhiteNoise
# ------------------------
STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")  # dossier cible de collectstatic

# (facultatif) si tu as un dossier /static dans le code source pour tes assets non collectés
STATICFILES_DIRS = [os.path.join(BASE_DIR, "static")]
# MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# -------------
# Cache Redis
# -------------
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": os.environ.get("REDIS_URL", "redis://127.0.0.1:6379/1"),
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        },
    }
}
# Connexion par email uniquement
ACCOUNT_LOGIN_METHODS = {"email"}
ACCOUNT_SIGNUP_FIELDS = ["email*", "first_name", "last_name", "password1*", "password2*"]

ACCOUNT_USER_MODEL_USERNAME_FIELD = None      # ✅ dit à allauth: pas de username
# ACCOUNT_USERNAME_REQUIRED = False             # (legacy, mais ok si encore lu)
ACCOUNT_USER_MODEL_EMAIL_FIELD = "email"
# ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_UNIQUE_EMAIL = True
# Email
ACCOUNT_EMAIL_VERIFICATION = "optional"  # ou "mandatory" en prod
ACCOUNT_CONFIRM_EMAIL_ON_GET = True
ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = True

# UX
ACCOUNT_RATE_LIMITS = {
    "login_failed": "5/5m",
    "signup": "10/h",
    "reset_password": "5/h",
}

ACCOUNT_ADAPTER = "compte.adapters.AccountAdapter"

# Redirections
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/account/login/"

# Formulaires custom (optionnel mais recommandé)
ACCOUNT_FORMS = {
    # "login": "compte.forms.LoginForm",
    "signup": "compte.forms.CustomSignupForm",
}
# -------------
# Celery + Redis
# -------------
CELERY_BROKER_URL = os.environ.get(
    "CELERY_BROKER_URL",
    "redis://127.0.0.1:6379/0",
)
CELERY_RESULT_BACKEND = os.environ.get(
    "CELERY_RESULT_BACKEND",
    CELERY_BROKER_URL,
)

CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = TIME_ZONE

# Pour django_celery_results
CELERY_RESULT_EXTENDED = True

# settings.py
AWS_ACCESS_KEY_ID = os.getenv("MINIO_ACCESS_KEY", "")
AWS_SECRET_ACCESS_KEY = os.getenv("MINIO_SECRET_KEY", "")
AWS_STORAGE_BUCKET_NAME = os.getenv("MINIO_BUCKET", "bestepargne")
AWS_S3_REGION_NAME = os.getenv("MINIO_REGION", "us-east-1")

# ✅ Endpoint interne (réseau docker) pour que Django upload sur MinIO
AWS_S3_ENDPOINT_URL = os.getenv("MINIO_ENDPOINT", "http://minio:9000")

# ✅ Domaine public (Traefik) pour que le navigateur charge les médias
# Exemple: MINIO_PUBLIC_DOMAIN=minio.ayo-group.com
AWS_S3_CUSTOM_DOMAIN = os.getenv("MINIO_PUBLIC_DOMAIN", "")

# SSL côté URL publique
AWS_S3_URL_PROTOCOL = "https:"  # Traefik termine en https
AWS_S3_USE_SSL = False          # IMPORTANT: Django parle à MinIO en http interne
AWS_S3_VERIFY = False

AWS_S3_SIGNATURE_VERSION = "s3v4"
AWS_DEFAULT_ACL = None
AWS_QUERYSTRING_AUTH = os.getenv("MINIO_QUERYSTRING_AUTH", "0") == "1"

DEFAULT_FILE_STORAGE = "storages.backends.s3boto3.S3Boto3Storage"
