# Generated by Django 4.2.27 on 2026-06-21

import django.core.validators
from django.db import migrations, models


def normalize_existing_ratings(apps, schema_editor):
    course_review = apps.get_model("reviews", "CourseReview")
    course_review.objects.filter(rating__lt=1).update(rating=1)
    course_review.objects.filter(rating__gt=5).update(rating=5)


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0002_coursereview_delete_review_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursereview",
            name="comment",
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name="coursereview",
            name="rating",
            field=models.PositiveSmallIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AddIndex(
            model_name="coursereview",
            index=models.Index(
                fields=["course", "is_public"],
                name="review_course_public_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="coursereview",
            index=models.Index(fields=["created_at"], name="review_created_at_idx"),
        ),
        migrations.RunPython(
            normalize_existing_ratings,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name="coursereview",
            constraint=models.CheckConstraint(
                check=models.Q(rating__gte=1, rating__lte=5),
                name="reviews_rating_1_5",
            ),
        ),
    ]
