# Generated by Django 4.2.27 on 2026-01-04 22:30

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=140, unique=True)),
            ],
            options={
                "verbose_name": "Catégorie",
                "verbose_name_plural": "Catégories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=220, unique=True)),
                ("subtitle", models.CharField(blank=True, max_length=220)),
                ("description", models.TextField(blank=True)),
                (
                    "course_type",
                    models.CharField(
                        choices=[
                            ("CERTIFIANTE", "Certifiante"),
                            ("PROFESSIONNELLE", "Professionnelle"),
                            ("ACADEMIQUE", "Académique"),
                            ("INTERNE", "Interne (RH / conformité)"),
                        ],
                        default="PROFESSIONNELLE",
                        max_length=20,
                    ),
                ),
                (
                    "pricing_type",
                    models.CharField(
                        choices=[
                            ("FREE", "Gratuit"),
                            ("PAID", "Payant"),
                            ("HYBRID", "Hybride"),
                        ],
                        default="PAID",
                        max_length=10,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("currency", models.CharField(default="XOF", max_length=8)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Brouillon"),
                            ("REVIEW", "En validation"),
                            ("PUBLISHED", "Publié"),
                            ("ARCHIVED", "Archivé"),
                        ],
                        default="DRAFT",
                        max_length=12,
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("company_only", models.BooleanField(default=False)),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True, null=True, upload_to="courses/thumbnails/"
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CourseSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("order", models.PositiveIntegerField(default=1)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("order", models.PositiveIntegerField(default=1)),
                (
                    "lesson_type",
                    models.CharField(
                        choices=[
                            ("VIDEO", "Vidéo"),
                            ("TEXT", "Texte"),
                            ("FILE", "Fichier"),
                            ("QUIZ", "Quiz"),
                            ("LIVE", "Live"),
                        ],
                        default="VIDEO",
                        max_length=10,
                    ),
                ),
                ("is_preview", models.BooleanField(default=False)),
                ("duration_sec", models.PositiveIntegerField(default=0)),
                ("content", models.TextField(blank=True)),
                ("video_url", models.URLField(blank=True)),
                (
                    "file",
                    models.FileField(blank=True, null=True, upload_to="courses/files/"),
                ),
            ],
            options={
                "ordering": ["section__order", "order"],
            },
        ),
        migrations.CreateModel(
            name="MediaAsset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("video", "Video"),
                            ("audio", "Audio"),
                            ("doc", "Document"),
                        ],
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(blank=True, default="", max_length=255)),
                ("object_key", models.CharField(max_length=1024, unique=True)),
                ("content_type", models.CharField(max_length=120)),
                ("size", models.BigIntegerField(default=0)),
                ("duration_seconds", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
