# Generated by Django 4.2.27 on 2026-01-04 22:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("catalog", "0001_initial"),
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mediaasset",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="media_assets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="media_asset",
            field=models.ForeignKey(
                blank=True,
                help_text="Fichier MinIO lié (video/audio/doc).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lessons",
                to="catalog.mediaasset",
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lessons",
                to="catalog.coursesection",
            ),
        ),
        migrations.AddField(
            model_name="coursesection",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sections",
                to="catalog.course",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="courses",
                to="catalog.category",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="internal_courses",
                to="organizations.company",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="instructor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="courses_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="mediaasset",
            index=models.Index(
                fields=["owner", "kind", "created_at"],
                name="catalog_med_owner_i_229390_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="lesson",
            index=models.Index(
                fields=["section", "order"], name="catalog_les_section_eb5100_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="lesson",
            unique_together={("section", "order")},
        ),
        migrations.AddIndex(
            model_name="coursesection",
            index=models.Index(
                fields=["course", "order"], name="catalog_cou_course__443d70_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="coursesection",
            unique_together={("course", "order")},
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(
                fields=["status", "pricing_type"], name="catalog_cou_status_453ef6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(fields=["slug"], name="catalog_cou_slug_db19fe_idx"),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(
                fields=["created_at"], name="catalog_cou_created_0a5ae1_idx"
            ),
        ),
    ]
