# Generated by Django 4.2.27 on 2026-01-05 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="preview_media_asset",
            field=models.ForeignKey(
                blank=True,
                help_text="Preview vidéo (MinIO) affichée en page cours.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="course_previews",
                to="catalog.mediaasset",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="preview_video_url",
            field=models.URLField(blank=True),
        ),
    ]
