# Generated by Django 4.2.27 on 2026-01-06 16:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("catalog", "0003_course_preview_media_asset_course_preview_video_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("COURSE", "Achat cours"),
                            ("SUBSCRIPTION", "Abonnement"),
                            ("OTHER", "Autre"),
                        ],
                        default="COURSE",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "En attente"),
                            ("PAID", "Payé"),
                            ("FAILED", "Échoué"),
                            ("CANCELED", "Annulé"),
                            ("REFUNDED", "Remboursé"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("reference", models.CharField(max_length=80, unique=True)),
                ("provider", models.CharField(blank=True, default="", max_length=40)),
                (
                    "provider_ref",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("currency", models.CharField(default="XOF", max_length=8)),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("meta", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "status"], name="catalog_pay_user_id_b95058_idx"
                    ),
                    models.Index(
                        fields=["reference"], name="catalog_pay_referen_b05195_idx"
                    ),
                    models.Index(
                        fields=["provider", "provider_ref"],
                        name="catalog_pay_provide_da6cb4_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=140)),
                ("body", models.TextField(blank=True, default="")),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("INFO", "Info"),
                            ("SUCCESS", "Succès"),
                            ("WARNING", "Alerte"),
                            ("DANGER", "Critique"),
                        ],
                        default="INFO",
                        max_length=10,
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "action_url",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_read", "created_at"],
                        name="catalog_not_user_id_6f4bf5_idx",
                    )
                ],
            },
        ),
    ]
