# Generated by Django 4.2.27 on 2026-03-17 12:27

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_payment_notification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="content",
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
