# Generated by Django 4.2.27 on 2026-04-06 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_alter_lesson_content"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="mediaasset",
            name="catalog_med_owner_i_229390_idx",
        ),
        migrations.AddField(
            model_name="mediaasset",
            name="bitrate",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mediaasset",
            name="height",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mediaasset",
            name="optimized_object_key",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="mediaasset",
            name="processing_error",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="mediaasset",
            name="processing_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("ready", "Ready"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="mediaasset",
            name="thumbnail_object_key",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="mediaasset",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="mediaasset",
            name="width",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="mediaasset",
            name="content_type",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="mediaasset",
            name="duration_seconds",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="mediaasset",
            name="kind",
            field=models.CharField(
                choices=[("video", "Video"), ("audio", "Audio"), ("doc", "Document")],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="mediaasset",
            name="object_key",
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AddIndex(
            model_name="mediaasset",
            index=models.Index(
                fields=["owner", "kind"], name="catalog_med_owner_i_eb5232_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mediaasset",
            index=models.Index(
                fields=["owner", "created_at"], name="catalog_med_owner_i_642c91_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mediaasset",
            index=models.Index(
                fields=["processing_status"], name="catalog_med_process_f09807_idx"
            ),
        ),
    ]
