# Generated by Django 4.2.27 on 2026-04-23 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0002_organization_organizationinvitation_and_more"),
        ("catalog", "0006_remove_mediaasset_catalog_med_owner_i_229390_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="internal_courses",
                to="organizations.organization",
            ),
        ),
    ]
