# Generated by Django 4.2.27 on 2026-07-09 14:34
# Correction manuelle R25 : convertie en SeparateDatabaseAndState + RunSQL
# idempotent car les index d'origine (`catalog_cou_course__b5b8c1_idx`,
# etc.) n'existent pas toujours en base (hash Django dépendant des
# versions / de l'ordre des Meta.indexes). Sans ce fix, `migrate` explose
# avec `ProgrammingError: relation "catalog_cou_course__b5b8c1_idx" does not exist`.
#
# Le comportement final est identique : Django state = nouveaux noms.
from django.db import migrations, models


def _rename_index_if_exists(old_name: str, new_name: str) -> migrations.RunSQL:
    """Rename PostgreSQL index only if the old name exists.

    Robuste au replay et aux bases où l'index a déjà été créé avec le nouveau
    nom (fresh install / squash).
    """
    return migrations.RunSQL(
        sql=(
            f"DO $$ BEGIN "
            f"IF EXISTS (SELECT 1 FROM pg_class WHERE relname = '{old_name}' AND relkind = 'i') "
            f"THEN ALTER INDEX \"{old_name}\" RENAME TO \"{new_name}\"; "
            f"END IF; END $$;"
        ),
        reverse_sql=(
            f"DO $$ BEGIN "
            f"IF EXISTS (SELECT 1 FROM pg_class WHERE relname = '{new_name}' AND relkind = 'i') "
            f"THEN ALTER INDEX \"{new_name}\" RENAME TO \"{old_name}\"; "
            f"END IF; END $$;"
        ),
    )


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0012_course_r10_enrichment"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                _rename_index_if_exists(
                    "catalog_cou_course__b5b8c1_idx",
                    "catalog_cou_course__c630e1_idx",
                ),
                _rename_index_if_exists(
                    "catalog_cou_actor__a4e7f3_idx",
                    "catalog_cou_actor_i_1eb1a4_idx",
                ),
                _rename_index_if_exists(
                    "catalog_cou_action__c2d9a8_idx",
                    "catalog_cou_action_6a7f29_idx",
                ),
            ],
            state_operations=[
                migrations.RenameIndex(
                    model_name="courselifecycleevent",
                    new_name="catalog_cou_course__c630e1_idx",
                    old_name="catalog_cou_course__b5b8c1_idx",
                ),
                migrations.RenameIndex(
                    model_name="courselifecycleevent",
                    new_name="catalog_cou_actor_i_1eb1a4_idx",
                    old_name="catalog_cou_actor__a4e7f3_idx",
                ),
                migrations.RenameIndex(
                    model_name="courselifecycleevent",
                    new_name="catalog_cou_action_6a7f29_idx",
                    old_name="catalog_cou_action__c2d9a8_idx",
                ),
            ],
        ),
        migrations.AlterField(
            model_name="courselifecycleevent",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
