# Generated by Django 4.2.27 on 2026-07-09 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0012_course_r10_enrichment"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="courselifecycleevent",
            new_name="catalog_cou_course__c630e1_idx",
            old_name="catalog_cou_course__b5b8c1_idx",
        ),
        migrations.RenameIndex(
            model_name="courselifecycleevent",
            new_name="catalog_cou_actor_i_1eb1a4_idx",
            old_name="catalog_cou_actor__a4e7f3_idx",
        ),
        migrations.RenameIndex(
            model_name="courselifecycleevent",
            new_name="catalog_cou_action_6a7f29_idx",
            old_name="catalog_cou_action__c2d9a8_idx",
        ),
        migrations.AlterField(
            model_name="courselifecycleevent",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
