# Generated by Django 4.2.27 on 2026-07-09 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0013_course_certificate_template"),
        (
            "catalog",
            "0013_rename_catalog_cou_course__b5b8c1_idx_catalog_cou_course__c630e1_idx_and_more",
        ),
    ]

    operations = []
