# Generated by Django 4.2.27 on 2026-07-09 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "certifications",
            "0006_rename_cert_tpl_owner_pub_idx_certificati_owner_i_e7c5fb_idx_and_more",
        ),
        ("catalog", "0014_merge_20260709_1817"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="certificate_template",
            field=models.ForeignKey(
                blank=True,
                help_text="Template appliqué aux certificats émis pour ce cours. Si NULL, le certificat utilise le template par défaut de la plateforme.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="courses",
                to="certifications.certificatetemplate",
            ),
        ),
    ]
