# Generated by Django 4.2.27 on 2026-01-04 22:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CertificateTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=160, unique=True)),
                (
                    "background",
                    models.ImageField(
                        blank=True, null=True, upload_to="certificates/templates/"
                    ),
                ),
                ("signature_name", models.CharField(blank=True, max_length=160)),
                ("signature_title", models.CharField(blank=True, max_length=160)),
            ],
        ),
        migrations.CreateModel(
            name="IssuedCertificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("issued_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("score_percent", models.PositiveIntegerField(default=0)),
                (
                    "serial",
                    models.CharField(editable=False, max_length=32, unique=True),
                ),
                (
                    "verification_hash",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True, null=True, upload_to="certificates/pdfs/"
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issued_certificates",
                        to="catalog.course",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="certifications.certificatetemplate",
                    ),
                ),
            ],
        ),
    ]
