# Generated by Django 4.2.27 on 2026-01-04 22:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("certifications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="issuedcertificate",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="certificates",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="issuedcertificate",
            unique_together={("user", "course")},
        ),
    ]
