# Generated by Django 4.2.27 on 2026-07-09 18:32
# Correction manuelle R25 : les RenameIndex sont wrappés dans un
# SeparateDatabaseAndState + RunSQL idempotent (IF EXISTS) pour ne PAS
# faire échouer `migrate` sur les bases où les anciens noms d'index
# (`cert_tpl_owner_pub_idx`, `cert_tpl_style_idx`) ne sont pas présents.
# Les AlterField restent classiques (idempotents par nature).
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def _rename_index_if_exists(old_name: str, new_name: str) -> migrations.RunSQL:
    return migrations.RunSQL(
        sql=(
            f"DO $$ BEGIN "
            f"IF EXISTS (SELECT 1 FROM pg_class WHERE relname = '{old_name}' AND relkind = 'i') "
            f"THEN ALTER INDEX \"{old_name}\" RENAME TO \"{new_name}\"; "
            f"END IF; END $$;"
        ),
        reverse_sql=(
            f"DO $$ BEGIN "
            f"IF EXISTS (SELECT 1 FROM pg_class WHERE relname = '{new_name}' AND relkind = 'i') "
            f"THEN ALTER INDEX \"{new_name}\" RENAME TO \"{old_name}\"; "
            f"END IF; END $$;"
        ),
    )


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("certifications", "0005_seed_certificate_presets"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                _rename_index_if_exists(
                    "cert_tpl_owner_pub_idx",
                    "certificati_owner_i_e7c5fb_idx",
                ),
                _rename_index_if_exists(
                    "cert_tpl_style_idx",
                    "certificati_style_1057c5_idx",
                ),
            ],
            state_operations=[
                migrations.RenameIndex(
                    model_name="certificatetemplate",
                    new_name="certificati_owner_i_e7c5fb_idx",
                    old_name="cert_tpl_owner_pub_idx",
                ),
                migrations.RenameIndex(
                    model_name="certificatetemplate",
                    new_name="certificati_style_1057c5_idx",
                    old_name="cert_tpl_style_idx",
                ),
            ],
        ),
        migrations.AlterField(
            model_name="certificatetemplate",
            name="accent_color",
            field=models.CharField(
                default="#eab308", help_text="Couleur d'accent / dorée.", max_length=9
            ),
        ),
        migrations.AlterField(
            model_name="certificatetemplate",
            name="body_text",
            field=models.TextField(
                blank=True,
                default="Ce certificat est décerné à {{student_name}} pour avoir complété avec succès la formation « {{course_title}} ».",
                help_text="Variables supportées : {{student_name}}, {{course_title}}, {{instructor_name}}, {{organization_name}}, {{completion_date}}, {{certificate_number}}, {{hours}}, {{score}}, {{verification_url}}",
            ),
        ),
        migrations.AlterField(
            model_name="certificatetemplate",
            name="font_family",
            field=models.CharField(
                default="Inter, system-ui, sans-serif", help_text="CSS font-family.", max_length=80
            ),
        ),
        migrations.AlterField(
            model_name="certificatetemplate",
            name="footer_text",
            field=models.CharField(
                blank=True, default="", help_text="Ex : mention légale, devise.", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="certificatetemplate",
            name="is_default",
            field=models.BooleanField(
                default=False,
                help_text="Preset appliqué par défaut aux nouveaux cours certifiants.",
            ),
        ),
        migrations.AlterField(
            model_name="certificatetemplate",
            name="is_public",
            field=models.BooleanField(
                default=False, help_text="Visible et utilisable par tous les instructeurs."
            ),
        ),
        migrations.AlterField(
            model_name="certificatetemplate",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="Propriétaire (NULL = preset global de la plateforme).",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="certificate_templates",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="certificatetemplate",
            name="primary_color",
            field=models.CharField(
                default="#0284c7", help_text="Couleur principale (hex #rrggbb).", max_length=9
            ),
        ),
        migrations.AlterField(
            model_name="certificatetemplate",
            name="text_color",
            field=models.CharField(
                default="#0f172a", help_text="Couleur du texte principal.", max_length=9
            ),
        ),
    ]
