# Generated by Django 4.2.27 on 2026-07-13 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0006_admin_center"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="aiactionapproval",
            new_name="ai_aiaction_user_id_236feb_idx",
            old_name="ai_appr_user_idx",
        ),
        migrations.RenameIndex(
            model_name="aiactionapproval",
            new_name="ai_aiaction_status_decf24_idx",
            old_name="ai_appr_status_idx",
        ),
        migrations.RenameIndex(
            model_name="aiauditlog",
            new_name="ai_aiauditl_created_f32685_idx",
            old_name="ai_audit_created_idx",
        ),
        migrations.RenameIndex(
            model_name="aiauditlog",
            new_name="ai_aiauditl_kind_df065a_idx",
            old_name="ai_audit_kind_idx",
        ),
        migrations.RenameIndex(
            model_name="aicontentversion",
            new_name="ai_aiconten_entity__b099f7_idx",
            old_name="ai_ctntver_ent_idx",
        ),
        migrations.RenameIndex(
            model_name="aicontentversion",
            new_name="ai_aiconten_origin_cf3328_idx",
            old_name="ai_ctntver_origin_idx",
        ),
        migrations.RenameIndex(
            model_name="aiconversation",
            new_name="ai_aiconver_user_id_6243e4_idx",
            old_name="ai_conv_user_last_idx",
        ),
        migrations.RenameIndex(
            model_name="aiconversation",
            new_name="ai_aiconver_organiz_2a0db2_idx",
            old_name="ai_conv_org_last_idx",
        ),
        migrations.RenameIndex(
            model_name="aicoursegeneration",
            new_name="ai_aicourse_user_id_341040_idx",
            old_name="ai_coursegen_user_idx",
        ),
        migrations.RenameIndex(
            model_name="aicoursegeneration",
            new_name="ai_aicourse_status_5b1917_idx",
            old_name="ai_coursegen_status_idx",
        ),
        migrations.RenameIndex(
            model_name="aiimagegeneration",
            new_name="ai_aiimageg_user_id_99cbf9_idx",
            old_name="ai_imggen_user_idx",
        ),
        migrations.RenameIndex(
            model_name="aiimagegeneration",
            new_name="ai_aiimageg_status_2a75a4_idx",
            old_name="ai_imggen_status_idx",
        ),
        migrations.RenameIndex(
            model_name="aiknowledgechunk",
            new_name="ai_aiknowle_documen_ac12d6_idx",
            old_name="ai_kbchunk_doc_idx_idx",
        ),
        migrations.RenameIndex(
            model_name="aiknowledgedocument",
            new_name="ai_aiknowle_space_i_f87d18_idx",
            old_name="ai_kbdoc_space_upd_idx",
        ),
        migrations.RenameIndex(
            model_name="aiknowledgedocument",
            new_name="ai_aiknowle_status_3ea7d1_idx",
            old_name="ai_kbdoc_status_idx",
        ),
        migrations.RenameIndex(
            model_name="aiknowledgespace",
            new_name="ai_aiknowle_scope_c2eff8_idx",
            old_name="ai_kbspace_scope_idx",
        ),
        migrations.RenameIndex(
            model_name="aimessage",
            new_name="ai_aimessag_convers_af7707_idx",
            old_name="ai_msg_conv_created_idx",
        ),
        migrations.RenameIndex(
            model_name="aiquota",
            new_name="ai_aiquota_target__f1834e_idx",
            old_name="ai_quota_ttype_idx",
        ),
        migrations.RenameIndex(
            model_name="aiquota",
            new_name="ai_aiquota_target__3d1be3_idx",
            old_name="ai_quota_org_idx",
        ),
        migrations.RenameIndex(
            model_name="airecommendation",
            new_name="ai_airecomm_user_id_2e7a44_idx",
            old_name="ai_reco_user_created_idx",
        ),
        migrations.RenameIndex(
            model_name="airecommendation",
            new_name="ai_airecomm_user_id_30617c_idx",
            old_name="ai_reco_user_cat_idx",
        ),
        migrations.RenameIndex(
            model_name="aitoolexecution",
            new_name="ai_aitoolex_created_02462f_idx",
            old_name="ai_toolex_created_idx",
        ),
        migrations.RenameIndex(
            model_name="aitoolexecution",
            new_name="ai_aitoolex_tool_ke_6c278f_idx",
            old_name="ai_toolex_key_idx",
        ),
        migrations.RenameIndex(
            model_name="aitoolexecution",
            new_name="ai_aitoolex_user_id_6eb102_idx",
            old_name="ai_toolex_user_idx",
        ),
        migrations.RenameIndex(
            model_name="aitoolexecution",
            new_name="ai_aitoolex_status_262acc_idx",
            old_name="ai_toolex_status_idx",
        ),
        migrations.RenameIndex(
            model_name="aiusagerecord",
            new_name="ai_aiusager_created_792e54_idx",
            old_name="ai_usage_created_idx",
        ),
        migrations.RenameIndex(
            model_name="aiusagerecord",
            new_name="ai_aiusager_user_id_ef0528_idx",
            old_name="ai_usage_user_idx",
        ),
        migrations.RenameIndex(
            model_name="aiusagerecord",
            new_name="ai_aiusager_organiz_a45049_idx",
            old_name="ai_usage_org_idx",
        ),
        migrations.RenameIndex(
            model_name="aiwebsearch",
            new_name="ai_aiwebsea_created_89e934_idx",
            old_name="ai_websrch_created_idx",
        ),
        migrations.RenameIndex(
            model_name="aiwebsearch",
            new_name="ai_aiwebsea_user_id_91ccd9_idx",
            old_name="ai_websrch_user_idx",
        ),
        migrations.AlterField(
            model_name="aiactionapproval",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="aiauditlog",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="aicontentversion",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="aiconversation",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="aicoursegeneration",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="aiimagegeneration",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="aiknowledgechunk",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="aiknowledgedocument",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="aiknowledgespace",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="aimessage",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="aimodel",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="aimodel",
            name="is_default",
            field=models.BooleanField(
                default=False,
                help_text="Si vrai, ce modèle est choisi par défaut pour son purpose.",
            ),
        ),
        migrations.AlterField(
            model_name="aimodel",
            name="model_name",
            field=models.CharField(
                help_text="Identifiant côté provider (ex: 'gpt-4o-mini', 'claude-sonnet-4-6').",
                max_length=120,
            ),
        ),
        migrations.AlterField(
            model_name="aiprovider",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="aiprovider",
            name="priority",
            field=models.PositiveSmallIntegerField(
                default=100,
                help_text="Ordre du routeur : plus bas = plus prioritaire dans les fallbacks.",
            ),
        ),
        migrations.AlterField(
            model_name="aiquota",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="aiquota",
            name="target_role",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Ex: 'learner', 'instructor', 'platform_admin' (si target_type=ROLE)",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="airecommendation",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="aitoolexecution",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="aiusagerecord",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="aiwebsearch",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
