# Generated by Django 4.2.27 on 2026-01-17 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("compte", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LearnerKYC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "education_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("COLLEGE", "Collège"),
                            ("LYCEE", "Lycée"),
                            ("BAC", "Bac"),
                            ("BTS_DUT", "BTS/DUT"),
                            ("LICENCE", "Licence"),
                            ("MASTER", "Master"),
                            ("DOCTORAT", "Doctorat"),
                            ("AUTRE", "Autre"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "goal",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("JOB", "Trouver un emploi"),
                            ("PROMOTION", "Évoluer / promotion"),
                            ("ENTREPRENEUR", "Lancer un business"),
                            ("SKILL", "Monter en compétences"),
                            ("CERTIF", "Obtenir une certification"),
                            ("AUTRE", "Autre"),
                        ],
                        max_length=20,
                    ),
                ),
                ("domain_interest", models.CharField(blank=True, max_length=120)),
                ("job_title", models.CharField(blank=True, max_length=120)),
                (
                    "availability",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("LT2", "Moins de 2h / semaine"),
                            ("H2_5", "2 à 5h / semaine"),
                            ("H5_10", "5 à 10h / semaine"),
                            ("GT10", "Plus de 10h / semaine"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, default="Côte d’Ivoire", max_length=80
                    ),
                ),
                ("city", models.CharField(blank=True, max_length=80)),
                (
                    "language",
                    models.CharField(blank=True, default="Français", max_length=40),
                ),
                ("accept_terms", models.BooleanField(default=False)),
                ("accept_marketing", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kyc",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
