# Generated by Django 4.2.27 on 2026-01-17 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compte", "0002_learnerkyc"),
    ]

    operations = [
        migrations.AddField(
            model_name="learnerkyc",
            name="onboarding_level",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="learnerkyc",
            name="onboarding_profile",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
