# Generated by Django 4.2.27 on 2026-04-23 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0003_learnerkyc_onboarding_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('LEARNER', 'Apprenant'), ('INSTRUCTOR', 'Formateur'), ('COMPANY_ADMIN', 'Admin Entreprise'), ('SUPERADMIN', 'Administrateur principal')], db_index=True, default='LEARNER', max_length=20),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role', 'is_active'], name='compte_user_role_c04f48_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['created_at'], name='compte_user_created_aad63b_idx'),
        ),
    ]
