# Generated by Django 4.2.27 on 2026-04-23 16:46

import compte.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compte", "0004_alter_user_role_user_compte_user_role_c04f48_idx_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", compte.models.UserManager()),
            ],
        ),
        migrations.RemoveIndex(
            model_name="user",
            name="compte_user_role_c04f48_idx",
        ),
        migrations.RemoveField(
            model_name="user",
            name="role",
        ),
        migrations.AddField(
            model_name="user",
            name="platform_role",
            field=models.CharField(
                choices=[
                    ("USER", "Utilisateur"),
                    ("PLATFORM_ADMIN", "Administrateur plateforme"),
                ],
                db_index=True,
                default="USER",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["platform_role", "is_active"],
                name="compte_user_platfor_bdb7ab_idx",
            ),
        ),
    ]
